### ISSUE TITLE
Question : Generic persist method for Vertex and Edge

### ISSUE THREAD

**Issue by satendrakumar06** [mpollmeier/gremlin-scala#149]
Hi,

I am trying to write a generic trait which can persist any vertex or edge like:
```
import com.thinkaurelius.titan.core.{TitanTransaction}
import gremlin.scala._


trait PersistanceFactory[T]{


  def persist(implicit tt:ScalaGraph[TitanTransaction]):Vertex= tt + this.asInstanceOf[T]


  def persist(from:Vertex, to:Vertex):Edge= from --- this.asInstanceOf[T] --> to
  
}
```
If any case class can extends this trait : 
```
@label("person")
case class Person(name: String, age:Int) extends  PersistanceFactory[Person]
```

Now I want to do like ;
```
implicit val graph= titanGraph.newTransaction.asScala
 val person = Person("SRK", 50).persist
```
I did lot of  search on google but did not find any solution. I got just [similar solution]( https://github.com/anvie/blueprints-scala)   i am using gramlin-scala so  I don't want to use this library.

Thanks.

**Comment by satendrakumar06** [comment]
I am able do like:
```
import com.thinkaurelius.titan.core.TitanTransaction
import gremlin.scala._

trait PersistanceFactory{

  def persist[T <: Product : Marshallable ](implicit tt:ScalaGraph[TitanTransaction]):Vertex= {
    tt + this.asInstanceOf[T]
  }

  def persist[T <: Product : Marshallable ](from:Vertex, to:Vertex):Edge= from --- this.asInstanceOf[T] --> to

}
```


For this I need to do:
```
    implicit val tt = titanGraph.newTransaction().asScala

    val person = Person("SRK", 50).persist[Person]
```
so I need to pass case class type in each call of persist. **It does not make sense**.

**Comment by mpollmeier** [comment]
Sorry but I don't understand what you're trying to achieve with the PersistenceFactory. If you just leave it aside and just want to persist a person, all you need to do is `graph + person` to persist it. Am I missing something?

If you really wanted to have something like the PersistenceFactory, I'd rather use type classes than inheritance.

**Comment by satendrakumar06** [comment]
@mpollmeier Thanks. Let me explain.
I have 40 case classes , some of are vertex and sum of them edges. I want to persist all case class into titan db. In my use case,  each case class should have own persist method to persist into Titan DB.
I want to avoid boilerplate so i am creating a trait which have generic persist method and each case class will extends it and get persist method.
for example: 

```
trait PersistanceFactory[T]{


  def persist(implicit tt:ScalaGraph[TitanTransaction]):Vertex= tt + this.asInstanceOf[T]


  def persist(from:Vertex, to:Vertex):Edge= from --- this.asInstanceOf[T] --> to

}


@label("person")
case class Person(name: String, age:Int) extends  PersistanceFactory[Person]

implicit val graph= titanGraph.newTransaction.asScala
 val person = Person("SRK", 50).persist

```

**Comment by joan38** [comment]
Although I don't understand what boilerplate code you save:
`val person = Person("SRK", 50).persist`
vs
`val person = graph + Person("SRK", 50)`

Trading 1 character for an implicit :/

This, should make you happy:
```scala
trait Persistable[T <: Product] {
  def persist(implicit g: ScalaGraph): ScalaVertex = g + this.asInstanceOf[T]
  def persist(from: Vertex, to: Vertex): ScalaEdge = from --- this.asInstanceOf[T] --> to
}
```

**Comment by satendrakumar06** [comment]
@joan38 Thanks for replay.

I am trying your suggestion. It is not working. Getting error;

```
scala.ScalaReflectionException: type T is not a class
[error] 	at scala.reflect.api.Symbols$SymbolApi$class.asClass(Symbols.scala:275)
[error] 	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:84)
[error] 	at gremlin.scala.Marshallable$.materializeMappableImpl(Marshallable.scala:114)
[error]     tt + this.asInstanceOf[T]
[error]        ^
[error] scala.ScalaReflectionException: type T is not a class
[error] 	at scala.reflect.api.Symbols$SymbolApi$class.asClass(Symbols.scala:275)
[error] 	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:84)
[error] 	at gremlin.scala.Marshallable$.materializeMappableImpl(Marshallable.scala:114)
[error]   def persist(from:Vertex, to:Vertex):Edge= from --- this.asInstanceOf[T] --> to
[error]                                               

```

**Comment by joan38** [comment]
I think I forgot the Type class `Marshallable`, so try with this one:
```scala
trait Persistable[CC <: Product: Marshallable] {
  def persist(implicit g: ScalaGraph): ScalaVertex = g + this.asInstanceOf[CC]
  def persist(from: Vertex, to: Vertex): ScalaEdge = from --- this.asInstanceOf[CC] --> to
}
```

**Comment by satendrakumar06** [comment]
@joan38 This would never compile.

**Comment by satendrakumar06** [comment]
@joan38 Getting error:
```
 traits cannot have type parameters with context bounds `: ...' nor view bounds `<% ...'
[error] trait Persistable[CC <: Product: Marshallable]

```

**Comment by satendrakumar06** [comment]
@mpollmeier Any luck ?

**Comment by joan38** [comment]
Ah yes I'm stupid.
I will have a look tonight. Pretty sure it's because of the Macros:

```scala
trait Persistable[CC <: Product: Marshallable] {
  private val cc = this.asInstanceOf[CC]
  def persist(implicit g: ScalaGraph): ScalaVertex = g + cc
  def persist(from: Vertex, to: Vertex): ScalaEdge = from --- cc --> to
}
```

**Comment by satendrakumar06** [comment]
@joan28 For me this is not working. could you please give full code.

**Comment by joan38** [comment]
This is the full code of the trait.
According to your error message `type T is not a class` I guess you just messed with the type parameter you named `T` and I name `CC`.

Could you please make a full copy and past instead of modifying your code.

**Comment by satendrakumar06** [comment]
See Error
```
[error] /home/satendra/demo/common/src/main/scala/com/knol/titan/persist/Persistable.scala:14: exception during macro expansion: 
[error] scala.ScalaReflectionException: type CC is not a class
[error] 	at scala.reflect.api.Symbols$SymbolApi$class.asClass(Symbols.scala:275)
[error] 	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:84)
[error] 	at gremlin.scala.Marshallable$.materializeMappableImpl(Marshallable.scala:114)
[error]   def persist(from: Vertex, to: Vertex): ScalaEdge = from --- this.asInstanceOf[CC] --> to
[error]                                                           ^

```

**Comment by joan38** [comment]
Actually you are right, the real way to do should be something like:
```scala
trait Persistable { self: Product =>
    def persist(implicit g: ScalaGraph[_]): ScalaVertex = g addVertex this
    def persist(from: Vertex, to: Vertex): ScalaEdge = from --- this --> to
}
```

But this doesn't work because of the Macros:
```
Error:(9, 61) not found: value <none>
    def persist(implicit g: ScalaGraph[_]): ScalaVertex = g addVertex this
```
Macros are something run at compile time and therefore it tries to take `this` and convert it to a Marshallable and that is not possible at this point as we are in a trait and we don't know yet what is the concret type.

**Comment by satendrakumar06** [comment]
@joan38 Thanks for the prompt reply I really appreciate your help.
Should I close this issue ?

**Comment by joan38** [comment]
Yes we can
