### ISSUE TITLE
dynamodb-titan using scala-2.12 is not working.

### ISSUE THREAD

**Issue by smdmts** [mpollmeier/gremlin-scala#179]
Hi, I'm new gremlin-scala user and trying to use dynamodb-titan in scala-2.12. But in the current version is not work well because `org.apache.tinkerpop` of the version is conflicting between dynamodb-titan  and gremlin-scala.

- dynamodb-titan
  - 3.0.1-incubating ( https://github.com/awslabs/dynamodb-titan-storage-backend/blob/1.0.0/pom.xml#L24 ) 
- gremlin-scala
  - 3.2.3 ( https://github.com/mpollmeier/gremlin-scala/blob/master/build.sbt#L6 )

Therefore, would you mind to confirmation this PR and publish maven central?
https://github.com/mpollmeier/gremlin-scala/pull/178

Thanks,

- sample build.sbt
```
scalaVersion := "2.12.0"
val titanV = "1.0.0"
libraryDependencies ++= Seq(
  "com.michaelpollmeier" %% "gremlin-scala" % "3.2.3.3",
  "com.thinkaurelius.titan" % "titan-core" % titanV,
  "org.scalatest" %% "scalatest" % "3.0.0" % "test"
)
resolvers += Resolver.mavenLocal
```

- stack trace.
```
A needed class was not found. This could be due to an error in your runpath. Missing class: org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategy$VendorOptimizationStrategy
java.lang.NoClassDefFoundError: org/apache/tinkerpop/gremlin/process/traversal/TraversalStrategy$VendorOptimizationStrategy
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<clinit>(StandardTitanGraph.java:86)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:94)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:74)
    at InMemoryConnect.connect(InMemoryConnect.scala:9)
    at InMemoryConnect.connect$(InMemoryConnect.scala:4)
```

**Comment by mpollmeier** [comment]
just released `3.0.2-incubating.2`, should sync to maven central in a few hours :)
