### ISSUE TITLE
Unable to create vertex when the case class has optional parameters

### ISSUE THREAD

**Issue by kusumakarb** [mpollmeier/gremlin-scala#251]
Whenever there is an Optional parameter in the case class, a property with key `__gs` is being added by `gremlin-scala` to the vertex properties. Since we have the disabled the [automatic schema maker](https://docs.janusgraph.org/latest/schema.html#_automatic_schema_maker), JanusGraph does not allow the creation of the property `__gs` without explicitly defining the schema for it, which results in the error.

```
java.lang.IllegalArgumentException: Property Key with given name does not exist: __gs
	at org.janusgraph.graphdb.types.typemaker.DisableDefaultSchemaMaker.makePropertyKey(DisableDefaultSchemaMaker.java:47)
	at org.janusgraph.core.schema.DefaultSchemaMaker.makePropertyKey(DefaultSchemaMaker.java:73)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.getOrCreatePropertyKey(StandardJanusGraphTx.java:995)
	at org.janusgraph.graphdb.vertices.AbstractVertex.property(AbstractVertex.java:152)
	at org.janusgraph.core.JanusGraphVertex.property(JanusGraphVertex.java:72)
	at org.janusgraph.graphdb.util.ElementHelper.attachProperties(ElementHelper.java:80)
	at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsTransaction.addVertex(JanusGraphBlueprintsTransaction.java:122)
	at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph.addVertex(JanusGraphBlueprintsGraph.java:140)
	at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph.addVertex(JanusGraphBlueprintsGraph.java:59)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.AddVertexStartStep.processNextStart(AddVertexStartStep.java:91)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:200)
	at gremlin.scala.ScalaGraph.addVertex(ScalaGraph.scala:36)
	at gremlin.scala.ScalaGraph.addVertex(ScalaGraph.scala:40)
	at gremlin.scala.ScalaGraph.addVertex(ScalaGraph.scala:51)
	at gremlin.scala.ScalaGraph.$plus(ScalaGraph.scala:54)
```
We are using `JanusGraph 0.3.0` and `gremlin-scala 3.3.3.4` . The automatic schema creation of Janusgraph is disabled. How to resolve this?

**Comment by mpollmeier** [comment]
Please post a minimal, complete and verifiable example, including build setup with all dependencies (e.g. build.sbt), ideally in a git repo. Thanks!

**Comment by kusumakarb** [comment]
Hi @mpollmeier,
Sorry for the insufficient information provided. I updated the above comment and also
please find the complete example as asked for [here](https://github.com/kusumakarb/gremlin-scala-janusgraph). This example reproduces the above error.

**Comment by mpollmeier** [comment]
sorry about the delay, I'm having a busy time right now. 
thanks for the repo - what am I supposed to run to reproduce your issue after starting janusgraph?

**Comment by kusumakarb** [comment]
That's fine, no problem with the delay. After you start the JanusGraph, you need to initialize the schema and run the object named `Crud` in the project. The [readme](https://github.com/kusumakarb/gremlin-scala-janusgraph/blob/master/README.md) of the project has the instructions about the same.

**Comment by mpollmeier** [comment]
Your sample project seems to have a problem:
```
gremlin> graph = JanusGraphFactory.open('conf/janusgraph-cassandra-es.properties')
==>standardjanusgraph[cassandrathrift:[127.0.0.1]]
gremlin> defineGraphSchema(graph)
Adding this property for key [~T$SchemaName] and value [rtname] violates a uniqueness constraint [SystemIndex#~T$SchemaName]
Type ':help' or ':h' for help.
Display stack trace? [yN]y
org.janusgraph.core.SchemaViolationException: Adding this property for key [~T$SchemaName] and value [rtname] violates a uniqueness constraint [SystemIndex#~T$SchemaName]
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addProperty(StandardJanusGraphTx.java:817)
```

Anyway, I just had a look and removing the `__gs` property was a TODO anyway, so I've just done that in https://github.com/mpollmeier/gremlin-scala/commit/2ddd6d015cf51bafa9ab826cd7e91814bed4e8a0, which should automatically be part of 3.3.3.19. Let me know if that works.

**Comment by kusumakarb** [comment]
Hi @mpollmeier 
I tested it with the version `3.3.3.24` and it works fine. 
Thank you.
