### ISSUE TITLE
toCC() key not found

### ISSUE THREAD

**Issue by darwinyip** [mpollmeier/gremlin-scala#276]
The following is giving me `key not found`

```
val serializer = new GryoMessageSerializerV3d0(GryoMapper.build.addRegistry(TinkerIoRegistryV3d0.instance))
val cluster: Cluster = Cluster.build.addContactPoint("localhost").port(8182).serializer(serializer).create
implicit val graph: ScalaGraph = EmptyGraph.instance.asScala.configure(_.withRemote(DriverRemoteConnection.using(cluster)))

@label("item")
case class VertexModel(id: Long, name: String)

val v = graph + VertexModel(10, "Kat")
v.toCC[VertexModel]
// java.util.NoSuchElementException: key not found: id
```

When querying for all vertices, it does show up:
```
graph.V.valueMap.toList
// List[java.util.Map[String,Object]] = List({name=[Kat], id=[10]})
```

**Comment by darwinyip** [comment]
Just upgraded to `"com.michaelpollmeier" %% "gremlin-scala" % "3.4.0.4"` and still getting an error:

```
java.lang.IllegalStateException: The property does not exist as the key has no associated value for the provided element: v[16496]:id
	at org.apache.tinkerpop.gremlin.structure.Property$Exceptions.propertyDoesNotExist(Property.java:155)
	at org.apache.tinkerpop.gremlin.structure.Element.lambda$value$1(Element.java:94)
	at org.apache.tinkerpop.gremlin.structure.Property.orElseThrow(Property.java:101)
	at org.apache.tinkerpop.gremlin.structure.Element.value(Element.java:94)
	at com.peeriq.tekken.BracketGraph$$anon$2.toCC(BracketGraph.scala:29)
	at com.peeriq.tekken.BracketGraph$$anon$2.toCC(BracketGraph.scala:29)
	at gremlin.scala.ScalaVertex.toCC(ScalaVertex.scala:12)
	at com.peeriq.tekken.BracketGraph$.getModel(BracketGraph.scala:29)
	at com.peeriq.tekken.WebServer$.$anonfun$fetchItem$1(Tekken.scala:40)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by mpollmeier** [comment]
hmm, I don't see anything that's obviously wrong, and this works fine with an in-memory tinkergraph. 
My guess would be that it's a bug in the (de)serialization, maybe related to the fact that your property is called `id`. Try to rename it. 
If the error persists, can you share a full setup so I can replicate?

**Comment by darwinyip** [comment]
I'll post some code later. But I did try removing `id`. It happens for any property, even renaming them still doesn't work.

**Comment by darwinyip** [comment]
```
name := "toygraph"

version := "0.1"

scalaVersion := "2.12.8"

// https://mvnrepository.com/artifact/com.michaelpollmeier/gremlin-scala
libraryDependencies ++= Seq(
  "com.michaelpollmeier" %% "gremlin-scala" % "3.4.0.4",
  "org.janusgraph" % "janusgraph-core" % "0.3.1",
  "org.janusgraph" % "janusgraph-cql" % "0.3.1",
  "org.apache.tinkerpop" % "gremlin-driver" % "3.3.3"
)
```

```
import gremlin.scala._
import org.apache.tinkerpop.gremlin.driver.Cluster
import org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteConnection
import org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0
import org.apache.tinkerpop.gremlin.structure.io.gryo.GryoMapper
import org.apache.tinkerpop.gremlin.structure.util.empty.EmptyGraph
import org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerIoRegistryV3d0

@label("item")
case class VertexModel(id: Long, name: String)

object ToyGraph extends App {
  val serializer = new GryoMessageSerializerV3d0(GryoMapper.build.addRegistry(TinkerIoRegistryV3d0.instance))
  val cluster: Cluster = Cluster.build.addContactPoint("localhost").port(8182).serializer(serializer).create
  implicit val graph: ScalaGraph = EmptyGraph.instance.asScala.configure(_.withRemote(DriverRemoteConnection.using(cluster)))

  val v = graph + VertexModel(10, "Kat")
  v.toCC[VertexModel]
}
```

**Comment by mpollmeier** [comment]
Yup I can confirm the bug. It's already going wrong when adding the vertex. Here's a simplified version:

```
case class VertexModel(name: String)
val v = graph + VertexModel("Kat")
println(v) //v[16552] -> ok
println(v.valueMap()) //Map() -> not ok
```

Note that you should be using `JanusGraphIoRegistry`, but that's not the problem here. 
```
val serializer = new GryoMessageSerializerV3d0(GryoMapper.build.addRegistry(JanusGraphIoRegistry.getInstance))
````

**Comment by mpollmeier** [comment]
Looks like it's a general issue with working with RemoteGraphs. Here's a simplified version of it, taking fancy stuff like case class serialization out of the picture, so you can just run it in an sbt console:

```
import gremlin.scala._
import org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0
import org.apache.tinkerpop.gremlin.driver.Cluster
import org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteConnection
import org.apache.tinkerpop.gremlin.structure.io.gryo.GryoMapper 
import org.apache.tinkerpop.gremlin.structure.util.empty.EmptyGraph
import org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry

val serializer = new GryoMessageSerializerV3d0(GryoMapper.build.addRegistry(JanusGraphIoRegistry.getInstance))
val cluster = Cluster.build.addContactPoint("localhost").port(8182).serializer(serializer).create
implicit val graph: ScalaGraph = EmptyGraph.instance.asScala.configure(_.withRemote(DriverRemoteConnection.using(cluster)))

graph.traversal.V.drop.iterate
graph.traversal.addV("VertexModel").property(Key("name"), "testName").iterate
graph.traversal.V.valueMap.head // {name=[testName]} -> yay :)
graph.traversal.V.head.valueMap // Map() -> nay :(
```

I'm guessing it would be the same when working with gremlin-java directly, and the only idea I have is that the remote driver is 'optimizing' things and doesn't serialize the vertex properties, but I don't really know :(

**Comment by darwinyip** [comment]
I found this SO post. https://stackoverflow.com/questions/45764199/janusgraph-cluster-always-returns-vertex-without-properties-referencevertex

Vertices from a remote graph are detached from the properties.

**Comment by darwinyip** [comment]
Found this. http://tinkerpop.apache.org/docs/3.3.3/reference/#_properties_of_elements

**Comment by mpollmeier** [comment]
It doesn't sound like there's an option to change that behaviour :(
So guess it's time to update the readme: don't use case classes with remote dbs.

**Comment by darwinyip** [comment]
FYI, this is from one of the Janusgraph/Tinkerpop/Gremlin contributors over in https://gitter.im/janusgraph/janusgraph


> We're generally recommending that users use JanusGraph Server instead and connect via withRemote to that. The reason is simply that you're then only using the Gremlin traversal API instead of the graph API as the graph API is mostly intended to be used internally by graph providers (like JanusGraph) and the graph API will probably be removed completely with TinkerPop 4. TinkerPop 4 however won't be released any time soon so you can continue using JanusGraph embedded if you want to

**Comment by mpollmeier** [comment]
> We're generally recommending that users use JanusGraph Server instead and connect via withRemote to that

Isn't that what we're doing if we downloaded janusgraph and started it using `bin/janusgraph.sh -v start`? At least, that's what I'm suggesting in https://github.com/mpollmeier/gremlin-scala-examples/blob/master/janusgraph/src/test/scala/SimpleSpec.scala#L47-L77

That test should probably be refactored to use the traversal api, but that won't make a difference for this problem, since janusgraph will still not attach the properties.

**Comment by mpollmeier** [comment]
added a warning to the readme in https://github.com/mpollmeier/gremlin-scala/commit/a20995af634419b0a1ad26784c8af4e057b5634d
we could probably work around this, but we'd be working against the tinkerpop best practices with remote graphs...
